use qmetaobject::prelude::*;

qrc!(pub resource_init,
    "res" {
        "qml/main.qml",
        "qml/MainWindow.qml",
        "qml/HomePage.qml",
        "qml/Footer.qml",
        "qml/About.qml",

        "qml/Header/Field.qml",
        "qml/Header/Left.qml",
        "qml/Header/Right.qml",

        "qml/Header/LeftBtnField/BtnField.qml",
        "qml/Header/LeftBtnField/Price.qml",

        "qml/Price/Panel.qml",
        "qml/Price/Header.qml",
        "qml/Price/DItem.qml",
        "qml/Price/PItem.qml",
        "qml/Price/Detail.qml",
        "qml/Price/MacroChara.qml",

        "qml/Setting/Panel.qml",
        "qml/Setting/Data.qml",
        "qml/Setting/Lang.qml",
        "qml/Setting/ShortKey.qml",
        "qml/Setting/UI.qml",

        "qml/ToolBox/Panel.qml",

        "qml/ToolBox/Cal/Panel.qml",
        "qml/ToolBox/Cal/ILOneStableCoin.qml",
        "qml/ToolBox/Cal/KellyFormula.qml",
        "qml/ToolBox/Cal/CompoundInterest.qml",

        "qml/ToolBox/AddrBook/Panel.qml",
        "qml/ToolBox/AddrBook/DItem.qml",
        "qml/ToolBox/AddrBook/Qrcode.qml",
        "qml/ToolBox/AddrBook/AddItem.qml",

        "qml/ToolBox/HandBook/Panel.qml",
        "qml/ToolBox/HandBook/DItem.qml",
        "qml/ToolBox/HandBook/SItem.qml",
        "qml/ToolBox/HandBook/SDItem.qml",
        "qml/ToolBox/HandBook/Footer.qml",
        "qml/ToolBox/HandBook/Chart.qml",
        "qml/ToolBox/HandBook/PaymentChart.qml",
        "qml/ToolBox/HandBook/IncomeChart.qml",

        "qml/ToolBox/FundBook/Panel.qml",
        "qml/ToolBox/FundBook/DItem.qml",
        "qml/ToolBox/FundBook/Footer.qml",

        "qml/ToolBox/BookMark/Panel.qml",
        "qml/ToolBox/BookMark/Left.qml",
        "qml/ToolBox/BookMark/LeftDItem.qml",
        "qml/ToolBox/BookMark/Right.qml",
        "qml/ToolBox/BookMark/RightDItem.qml",
        "qml/ToolBox/BookMark/LeftHeaderBar.qml",
        "qml/ToolBox/BookMark/RightHeaderBar.qml",

        "qml/ToolBox/Note/Panel.qml",
        "qml/ToolBox/Note/Left.qml",
        "qml/ToolBox/Note/LeftDItem.qml",
        "qml/ToolBox/Note/LeftHeaderBar.qml",
        "qml/ToolBox/Note/Right.qml",

        "qml/ToolBox/ContractStats/Panel.qml",
        "qml/ToolBox/ContractStats/Chart.qml",
        "qml/ToolBox/ContractStats/DItem.qml",

        "qml/ShortKey.qml",
        "qml/UtilityFn.qml",

        "qml/Base/Theme.qml",
        "qml/Base/ItemText.qml",
        "qml/Base/ItemLabel.qml",
        "qml/Base/SettingField.qml",
        "qml/Base/NumInput.qml",
        "qml/Base/ImageButton.qml",
        "qml/Base/LiveCircle.qml",
        "qml/Base/RadioButton.qml",
        "qml/Base/CheckBox.qml",
        "qml/Base/ComBox.qml",
        "qml/Base/SearchBar.qml",
        "qml/Base/Switch.qml",
        "qml/Base/Tip.qml",
        "qml/Base/SelectBox.qml",
        "qml/Base/TxtField.qml",
        "qml/Base/SlideBar.qml",
        "qml/Base/SBar.qml",
        "qml/Base/ProgBar.qml",
        "qml/Base/BDial.qml",
        "qml/Base/TxtButton.qml",
        "qml/Base/TxtArea.qml",
        "qml/Base/MsgBox.qml",
        "qml/Base/MsgTip.qml",
        "qml/Base/BTab.qml",
        "qml/Base/InputBar.qml",
        "qml/Base/Sep.qml",
        "qml/Base/TimeLineSeriesChart.qml",
        "qml/Base/DashLine.qml",
        "qml/Base/FloatLabel.qml",
        "qml/Base/LabelTxtField.qml",
        "qml/Base/DragArea.qml",
        "qml/Base/CDialog.qml",
        "qml/Base/CPieChart.qml",
        "qml/Base/NewsItem.qml",
        "qml/Base/DebugLog.qml",
        "qml/Base/SPage.qml",
        "qml/Base/Carousel.qml",

        "qml/Base/ItemPanel/DItem.qml",
        "qml/Base/ItemPanel/PItem.qml",
        "qml/Base/ItemPanel/Header.qml",
        "qml/Base/ItemPanel/Panel.qml",

        "image/icon.png",
        "image/exit.png",
        "image/setting.png",
        "image/refresh.png",
        "image/theme.png",
        "image/max-height.png",
        "image/minus.png",
        "image/add.png",
        "image/add2.png",
        "image/open.png",
        "image/search.png",
        "image/clear.png",
        "image/home.png",
        "image/note.png",
        "image/bell.png",
        "image/warn.png",
        "image/info.png",
        "image/tool-box.png",
        "image/blockchain.png",
        "image/chain.png",
        "image/chart.png",
        "image/qrcode.png",
        "image/edit.png",
        "image/copy.png",
        "image/up.png",
        "image/down.png",
        "image/save.png",
        "image/up-join.png",
        "image/about.png",
        "image/eye-hiden.png",
        "image/browser.png",
        "image/logout.png",
        "image/news.png",
        "image/exchange.png",
        "image/monitor.png",
        "image/stablecoin.png",
        "image/pool.png",
        "image/wallet.png",
        "image/account.png",
        "image/address.png",
        "image/red-circle.png",
        "image/green-circle.png",
        "image/link-break.png",
        "image/debug.png",
        "image/recovery.png",
        "image/preview.png",
        "image/rename.png",
        "image/like.png",
        "image/unlike.png",
        "image/notify.png",
        "image/notify-red.png",
    }
);
