use qmetaobject::prelude::*;

qrc!(pub resource_init,
    "res" {
        "qml/main.qml",
        "qml/PopupPanel.qml",
        "qml/PricePanel.qml",
        "qml/PricePanelHeader.qml",
        "qml/PricePanelFooter.qml",
        "qml/PriceDetail.qml",
        "qml/SettingPanel.qml",
        "qml/ShortKey.qml",
        "qml/UtilityFn.qml",

        "qml/Base/Theme.qml",
        "qml/Base/ItemText.qml",
        "qml/Base/ItemLabel.qml",
        "qml/Base/SettingField.qml",
        "qml/Base/NumInput.qml",
        "qml/Base/ImageButton.qml",
        "qml/Base/LiveCircle.qml",
        "qml/Base/RadioButton.qml",
        "qml/Base/CheckBox.qml",
        "qml/Base/ComBox.qml",
        "qml/Base/SearchBar.qml",
        "qml/Base/Switch.qml",
        "qml/Base/Tip.qml",
        "qml/Base/SelectBox.qml",
        "qml/Base/TxtField.qml",
        "qml/Base/SlideBar.qml",
        "qml/Base/SBar.qml",
        "qml/Base/ProgBar.qml",
        "qml/Base/BDial.qml",

        "image/exit.png",
        "image/setting.png",
        "image/refresh.png",
        "image/theme.png",
        "image/max-height.png",
        "image/minus.png",
        "image/add.png",
        "image/search.png",
    }
);
