use qmetaobject::prelude::*;

qrc!(pub resource_init,
    "res" {
        "qml/main.qml",
        "qml/HomePage.qml",
        "qml/Header.qml",
        "qml/Footer.qml",

        "qml/Price/Panel.qml",
        "qml/Price/Header.qml",
        "qml/Price/DItem.qml",
        "qml/Price/PItem.qml",
        "qml/Price/Detail.qml",

        "qml/Setting/Panel.qml",
        "qml/Setting/Data.qml",
        "qml/Setting/Lang.qml",
        "qml/Setting/ShortKey.qml",
        "qml/Setting/UI.qml",
        "qml/Setting/Test.qml",

        "qml/Note/Panel.qml",

        "qml/Todo/Panel.qml",
        "qml/Todo/DItem.qml",

        "qml/ShortKey.qml",
        "qml/UtilityFn.qml",
        "qml/SigSlot.qml",

        "qml/Base/Theme.qml",
        "qml/Base/ItemText.qml",
        "qml/Base/ItemLabel.qml",
        "qml/Base/SettingField.qml",
        "qml/Base/NumInput.qml",
        "qml/Base/ImageButton.qml",
        "qml/Base/LiveCircle.qml",
        "qml/Base/RadioButton.qml",
        "qml/Base/CheckBox.qml",
        "qml/Base/ComBox.qml",
        "qml/Base/SearchBar.qml",
        "qml/Base/Switch.qml",
        "qml/Base/Tip.qml",
        "qml/Base/SelectBox.qml",
        "qml/Base/TxtField.qml",
        "qml/Base/SlideBar.qml",
        "qml/Base/SBar.qml",
        "qml/Base/ProgBar.qml",
        "qml/Base/BDial.qml",
        "qml/Base/TxtButton.qml",
        "qml/Base/TxtArea.qml",
        "qml/Base/MsgBox.qml",

        "image/exit.png",
        "image/setting.png",
        "image/refresh.png",
        "image/theme.png",
        "image/max-height.png",
        "image/minus.png",
        "image/add.png",
        "image/search.png",
        "image/clear.png",
        "image/home.png",
        "image/note.png",
        "image/bell.png",
        "image/warn.png",
        "image/info.png",
        "image/todo-list.png",
    }
);
